server:
  port: 3400
  servlet:
    context-path: /server
eureka:
  instance:
    prefer-ip-address: true
    instance-id: server
  client:
    service-url:
      defaultZone: http://127.0.0.1:3101/eureka/eureka/


spring:
  application:
    name: server
  aop:
    proxy-target-class: true