server:
  port: 3101
  servlet:
    context-path: /eureka

eureka:
  instance:
    hostname: eureka1
    instance-id: eureka-1
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: eureka

